version: '3.8'
services:
  test12_db:
    image: mysql:8.0
    container_name: test12_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pks4kUlpU9Te0zxV
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: pks4kUlpU9Te0zxV
    volumes:
    - test12_db_data:/var/lib/mysql
    networks:
    - test12_network
  test12_wordpress:
    depends_on:
    - test12_db
    image: wordpress:latest
    container_name: test12_wp
    restart: unless-stopped
    ports:
    - 9006:80
    environment:
      WORDPRESS_DB_HOST: test12_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: pks4kUlpU9Te0zxV
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - test12_wp_data:/var/www/html
    networks:
    - test12_network
volumes:
  test12_db_data: {}
  test12_wp_data: {}
networks:
  test12_network:
    driver: bridge
