<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'pks4kUlpU9Te0zxV' );
define( 'DB_HOST', 'test12_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         'BZB]y-671@#)n%z*muqrmkpL#$>L3o-%]#th9nJxKC$5%(f$b_3_MBqU7<!9bSAJ' );
define( 'SECURE_AUTH_KEY',  '6(ADt1oUj&kQ]pp*t5LjD[PI3oI0g>[nrJ<rBjYBuHFYtIvMzux[m7YW0^2SSNVC' );
define( 'LOGGED_IN_KEY',    'ZaO670dJVBOk%yXHy!HXVPbv[fuVHJi=QHx8C#bf19!S03}8Kj[gj(2VWVRygPl4' );
define( 'NONCE_KEY',        '34vgaSCv[eL7yINGN5Dzk%W#lYUFcb!XGgBNJ4AbE_6lft9&pDc6@l8y*1WbLYM7' );
define( 'AUTH_SALT',        'hCrX_eX{TKgiMl0MORcW*-[*4Q}9NJZ2E*$D0M8du8z^wKbeZUIxBb619$wP!#Zf' );
define( 'SECURE_AUTH_SALT', 'Pn*K$_H}@HbF^>}]@ni1TwR}#ul%W&r_ltz>cN#*2_63T07Co>#Cwlc8TOuKf!qy' );
define( 'LOGGED_IN_SALT',   '6_4]$B5mYFX%-b2pkHy*Z-wXFKir5i]ZPOS7<<W](8]j]SnuApv=BlKW%MUX96ro' );
define( 'NONCE_SALT',       '}oBEKL6H8}lvsOBD[7BhyJ1*_]0iMgKLX3eIAR21yl&d2GJsfBgW&mZ[Q)@uSqs-' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );
// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);


// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
