version: '3.8'
services:
  test7_db:
    image: mysql:8.0
    container_name: test7_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 8BIWNKNASG9I1ybf
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 8BIWNKNASG9I1ybf
    volumes:
    - test7_db_data:/var/lib/mysql
    networks:
    - test7_network
  test7_wordpress:
    depends_on:
    - test7_db
    image: wordpress:latest
    container_name: test7_wp
    restart: unless-stopped
    ports:
    - 9003:80
    environment:
      WORDPRESS_DB_HOST: test7_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 8BIWNKNASG9I1ybf
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - test7_wp_data:/var/www/html
    - ./wp-config.php:/var/www/html/wp-config.php
    networks:
    - test7_network
volumes:
  test7_db_data: {}
  test7_wp_data: {}
networks:
  test7_network:
    driver: bridge
