<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', '8BIWNKNASG9I1ybf' );
define( 'DB_HOST', 'test7_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         'RZ$cSH_P{T<0yxexY}W>>HUv!)g^Y^V6_2$7wLX&UkhQnR&G1u921i(O4)$T{I^>' );
define( 'SECURE_AUTH_KEY',  '3c)hX&F(UF!h(V>mO)PTz!m_O2b7voajV{R-*9]sxwqDV9b%PdPG*12QH(23$(ze' );
define( 'LOGGED_IN_KEY',    'j&lledwFs7{&ZZWS5iL&06Dvp$8_Ku(N)>3RDeD!8tpkfDd[RC2bUoC{!nXXJvwg' );
define( 'NONCE_KEY',        'B=Qm}hPgicH<Ba^#1FyQw7NXq0_xg[*}uS_PT7@Y}pys=xG9WAIF]fS<5P3juL_v' );
define( 'AUTH_SALT',        '{Ke6G90W)Clp-NLCs!4H@JLaJc[]p10Kv%VpEk44(ngpvtAb=Z1gFEc5-m0e[xY>' );
define( 'SECURE_AUTH_SALT', 'Fv<pV$iJz7)4*EWKogJL7}(<^M4xnj-=7XGWE!]yCov9p@o&LPK<yq1ipBg-Kl23' );
define( 'LOGGED_IN_SALT',   '0&HcK[7#%xZQ&v_4QG4^T*FeC%Vfi]xmw6Z*[*r*>wTdn-A2&9!R%nCxR$XaJ<%k' );
define( 'NONCE_SALT',       '>gv!onKuJ]&IfDArfxu2Wpx-S#$_1T&@g<Kd1EmT![vJY#TquMLsO&W!(_MGMKkX' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );
// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);


// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
