version: '3.8'
services:
  dem_db:
    image: mysql:8.0
    container_name: dem_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: HpOc9QaexSZJiBPW
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: HpOc9QaexSZJiBPW
    volumes:
    - dem_db_data:/var/lib/mysql
    networks:
    - dem_network
  dem_wordpress:
    depends_on:
    - dem_db
    image: wordpress:latest
    container_name: dem_wp
    restart: unless-stopped
    ports:
    - 9003:80
    environment:
      WORDPRESS_DB_HOST: dem_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: HpOc9QaexSZJiBPW
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - dem_wp_data:/var/www/html
    networks:
    - dem_network
volumes:
  dem_db_data: {}
  dem_wp_data: {}
networks:
  dem_network:
    driver: bridge
