"""
WordPress Orchestrator - Core logic for provisioning WordPress instances
"""
import os
import socket
import yaml
from pathlib import Path
from django.conf import settings


def find_available_port(start_port=9000, end_port=9999):
    """
    Find an available port in the specified range
    Checks both network availability and database assignments
    """
    # Import here to avoid circular dependency
    from .models import WordPressSite
    
    # Get all ports already assigned in database
    assigned_ports = set(WordPressSite.objects.values_list('port', flat=True))
    
    for port in range(start_port, end_port + 1):
        # Skip if port is already assigned in database
        if port in assigned_ports:
            continue
            
        # Check if port is available on the network
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            try:
                sock.bind(('127.0.0.1', port))
                return port
            except OSError:
                continue
    raise RuntimeError(f"No available ports in range {start_port}-{end_port}")


def generate_docker_compose(site_name, db_password, port):
    """
    Generate docker-compose.yml configuration for a WordPress site
    
    Args:
        site_name: Name of the site (used for container names)
        db_password: MySQL root password
        port: Host port to map to WordPress container
    
    Returns:
        dict: Docker Compose configuration
    """
    compose_config = {
        'version': '3.8',
        'services': {
            f'{site_name}_db': {
                'image': 'mysql:8.0',
                'container_name': f'{site_name}_mysql',
                'restart': 'unless-stopped',
                'environment': {
                    'MYSQL_ROOT_PASSWORD': db_password,
                    'MYSQL_DATABASE': 'wordpress',
                    'MYSQL_USER': 'wordpress',
                    'MYSQL_PASSWORD': db_password,
                },
                'volumes': [
                    f'{site_name}_db_data:/var/lib/mysql'
                ],
                'networks': [
                    f'{site_name}_network'
                ]
            },
            f'{site_name}_wordpress': {
                'depends_on': [
                    f'{site_name}_db'
                ],
                'image': 'wordpress:latest',
                'container_name': f'{site_name}_wp',
                'restart': 'unless-stopped',
                'ports': [
                    f'{port}:80'
                ],
                'environment': {
                    'WORDPRESS_DB_HOST': f'{site_name}_db:3306',
                    'WORDPRESS_DB_USER': 'wordpress',
                    'WORDPRESS_DB_PASSWORD': db_password,
                    'WORDPRESS_DB_NAME': 'wordpress',
                },
                'volumes': [
                    f'{site_name}_wp_data:/var/www/html'
                ],
                'networks': [
                    f'{site_name}_network'
                ]
            }
        },
        'volumes': {
            f'{site_name}_db_data': {},
            f'{site_name}_wp_data': {}
        },
        'networks': {
            f'{site_name}_network': {
                'driver': 'bridge'
            }
        }
    }
    
    return compose_config


def generate_wp_config_content(db_host, db_name, db_user, db_password):
    """
    Generate the content for wp-config.php
    """
    import secrets
    
    def generate_salt():
        return ''.join(secrets.choice('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()-_=[]{}<>') for _ in range(64))

    return f"""<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', '{db_name}' );
define( 'DB_USER', '{db_user}' );
define( 'DB_PASSWORD', '{db_password}' );
define( 'DB_HOST', '{db_host}' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         '{generate_salt()}' );
define( 'SECURE_AUTH_KEY',  '{generate_salt()}' );
define( 'LOGGED_IN_KEY',    '{generate_salt()}' );
define( 'NONCE_KEY',        '{generate_salt()}' );
define( 'AUTH_SALT',        '{generate_salt()}' );
define( 'SECURE_AUTH_SALT', '{generate_salt()}' );
define( 'LOGGED_IN_SALT',   '{generate_salt()}' );
define( 'NONCE_SALT',       '{generate_salt()}' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
$protocol = 'http';

// Detect HTTPS from various sources (Cloudflare Tunnel, reverse proxy, etc.)
if (
    (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ||
    (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') ||
    (!empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] === 'on') ||
    (!empty($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == 443)
) {{
    $protocol = 'https';
    $_SERVER['HTTPS'] = 'on';
}}

if (isset($_SERVER['HTTP_HOST'])) {{
    define('WP_HOME', $protocol . '://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', $protocol . '://' . $_SERVER['HTTP_HOST']);
}}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {{
    define( 'ABSPATH', __DIR__ . '/' );
}}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
"""


def write_wp_config(site_directory, content):
    """Write wp-config.php to the site directory"""
    config_path = Path(site_directory) / 'wp-config.php'
    
    with open(config_path, 'w') as f:
        f.write(content)
    
    return str(config_path)


def write_docker_compose(site_directory, compose_config):
    """Write docker-compose.yml to the site directory"""
    compose_path = Path(site_directory) / 'docker-compose.yml'
    
    with open(compose_path, 'w') as f:
        yaml.dump(compose_config, f, default_flow_style=False, sort_keys=False)
    
    return str(compose_path)


def generate_nginx_config(site_name, domain, port):
    """
    Generate Nginx server block configuration
    
    Args:
        site_name: Name of the site
        domain: Local domain (e.g., mysite.local)
        port: Port where WordPress is running
    
    Returns:
        str: Nginx configuration content
    """
    config = f"""server {{
    listen 80;
    server_name {domain};

    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"""
    return config


def create_site_directory(site_name):
    """Create directory structure for a WordPress site"""
    sites_dir = settings.WORDPRESS_SITES_DIR
    site_dir = sites_dir / site_name
    
    # Create directories
    os.makedirs(site_dir, exist_ok=True)
    os.makedirs(sites_dir, exist_ok=True)
    
    return str(site_dir)
