tunnel: f7a24d5d-ea18-477f-bd26-6dfc0f3b2774
credentials-file: /home/adarsha/.cloudflared/f7a24d5d-ea18-477f-bd26-6dfc0f3b2774.json
ingress:
- hostname: dashboard.edubricz.online
  service: http://localhost:5173
- hostname: api.edubricz.online
  service: http://localhost:8000
- hostname: db.edubricz.online
  service: http://172.27.0.12:8080
- hostname: test23.edubricz.online
  service: http://localhost:9003
- hostname: test24.edubricz.online
  service: http://localhost:9004
- hostname: test25.edubricz.online
  service: http://localhost:9005
- hostname: test26.edubricz.online
  service: http://localhost:9006
- hostname: test27.edubricz.online
  service: http://localhost:9007
- hostname: test28.edubricz.online
  service: http://localhost:9008
- hostname: test29.edubricz.online
  service: http://localhost:9009
- hostname: test30.edubricz.online
  service: http://localhost:9010
- hostname: test31.edubricz.online
  service: http://localhost:9011
- hostname: test33.edubricz.online
  service: http://localhost:9012
- service: http_status:404
