tunnel: f7a24d5d-ea18-477f-bd26-6dfc0f3b2774
credentials-file: /home/adarsha/.cloudflared/f7a24d5d-ea18-477f-bd26-6dfc0f3b2774.json
ingress:
- hostname: dashboard.edubricz.online
  service: http://localhost:5173
- hostname: api.edubricz.online
  service: http://localhost:8088
- hostname: db.edubricz.online
  service: http://localhost:8080
- hostname: files.edubricz.online
  service: http://172.27.0.100:80
- hostname: test1.edubricz.online
  service: http://localhost:9000
- hostname: react-django.edubricz.online
  service: http://localhost:9003
- hostname: test4.edubricz.online
  service: http://localhost:9005
- hostname: student-crud.edubricz.online
  service: http://localhost:9007
- hostname: dfewrg.edubricz.online
  service: http://localhost:9012
- hostname: ad.edubricz.online
  service: http://localhost:9003
- hostname: kll.edubricz.online
  service: http://localhost:9012
- hostname: shop.edubricz.online
  service: http://localhost:9015
- hostname: test81.edubricz.online
  service: http://localhost:9023
- hostname: rdscheck90474.edubricz.online
  service: http://localhost:9004
- hostname: tes1.edubricz.online
  service: http://localhost:9026
- hostname: ple.edubricz.online
  service: http://localhost:9027
- hostname: testing1.edubricz.online
  service: http://localhost:9024
- service: http_status:404
