import os
import django
import sys

# Add the project root to the path
sys.path.append('/home/adarsha/Desktop/projects/HOST/host/backend')

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from django.db import connection

# Create the django_site table
with connection.cursor() as cursor:
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS "django_site" (
            "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "domain" varchar(100) NOT NULL,
            "name" varchar(50) NOT NULL
        );
    """)
    print("django_site table created successfully")
    
    # Insert default site
    cursor.execute("""
        INSERT INTO django_site (id, domain, name)
        VALUES (1, 'localhost:8000', 'Local Development')
        ON CONFLICT (id) DO NOTHING;
    """)
    print("Default site record created")
