<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'wordpress' );
define( 'DB_HOST', 'test18_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         '*PfPTZQ!rllj^AakYn99cp544j&^0SP!q=pPYM]9yhvzjf)q)tEwin84Ka6EB2YC' );
define( 'SECURE_AUTH_KEY',  'iBAA2sal2dWXYo@9n[k>xDq^P7ws<y4h4Bk23))FfLV5-BXhmsJGfZs37A$>C]-W' );
define( 'LOGGED_IN_KEY',    '#XXqj-H^MsrqQ7fx!YaP{Wr4OpgZ@E4DAb>Lwl3<V8ih&6dbJ9!o-NC5m[KTOjar' );
define( 'NONCE_KEY',        'W->8m7>9w3-F}DxyIU[2Ci6qa5Qr1fv<M=p#q*FNgaq3rJ2eG*rjRhQa>!=L}HU=' );
define( 'AUTH_SALT',        'i8Vn]fQQ02fH^U97gNXK6CrmvrY90&I4)>P0hVy%}lb^Dk&dFMKipIio@<NizLD{' );
define( 'SECURE_AUTH_SALT', ']isCb{$hU^&5wgb]T}$8ygxaA&!X*hq_Q[nmi^7e_Kxw00p4*8j)U$Oes&=emTUu' );
define( 'LOGGED_IN_SALT',   'r{Ct)Jen{p]AM=y%uGAq@rJV^HRvB$Y_w67Bf8}BQ}ziRF547)pw>sl<qkogJnCx' );
define( 'NONCE_SALT',       '8Q]ffZ[0QmR86Cv=F>TGKA9DR4nPAA@WCuBeig[%@6u^{HDA}S7H9GNyGN591$QZ' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
$protocol = 'http';

// Detect HTTPS from various sources (Cloudflare Tunnel, reverse proxy, etc.)
if (
    (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ||
    (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') ||
    (!empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] === 'on') ||
    (!empty($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == 443)
) {
    $protocol = 'https';
    $_SERVER['HTTPS'] = 'on';
}

if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', $protocol . '://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', $protocol . '://' . $_SERVER['HTTP_HOST']);
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
