<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'aNYqZpl12fh0Suzb' );
define( 'DB_HOST', 'test18_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         'L)en6]VJBN>YNn!OIbx-9SkyLyWeg{V=)Zp5XF3rFJ4C{wq[Y$OLvhgH%mmdyGax' );
define( 'SECURE_AUTH_KEY',  'kC#M@<He27UnyX10K=}>v42gWYt@O70xqyXiS2B_Ogts*Zo=T332kq>4UBJXx]Dj' );
define( 'LOGGED_IN_KEY',    '1B(MgE<Ipm7u-s6@JEoAAdnJsQ]@<pu<UmTzP2LKhmIZv(SnzXMuesMYK}Y_zSZ}' );
define( 'NONCE_KEY',        'vv<[wsLAGPg*DZ4h3ZtZqrH_JAF%2^28GE>QVgN3p8dL6Ue9Ajz^L2]xK%3UVZOu' );
define( 'AUTH_SALT',        'Pr9oPF%E=__<k3gx^Ru4W71eu<_uZ4xLHZ(<<TgCgaWq(chc5)<E0V2VXALF$VMj' );
define( 'SECURE_AUTH_SALT', '<P!mAfK2Za{{$AaT2]r[D1WvXn99!!OPsJiNJO1r5>Lfgw_FcXCvK1nwLOHw!CPW' );
define( 'LOGGED_IN_SALT',   '6_lsSFXp_ZX3Cwvps_X7wNi!b&UtHdMR9h%_BCl0O}79Nn9Bnpr@o2L&P-nj()gR' );
define( 'NONCE_SALT',       'Q{y38U6g)-nr4{*P#LU=igGZfSJUXz[VuZ=<U!9j4M!-2PV^^[Q9<zft}7rTIcRg' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
