version: '3.8'
services:
  test5_db:
    image: mysql:8.0
    container_name: test5_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: CCncxHvYPDJbZgks
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: CCncxHvYPDJbZgks
    volumes:
    - test5_db_data:/var/lib/mysql
    networks:
    - test5_network
  test5_wordpress:
    depends_on:
    - test5_db
    image: wordpress:latest
    container_name: test5_wp
    restart: unless-stopped
    ports:
    - 9001:80
    environment:
      WORDPRESS_DB_HOST: test5_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: CCncxHvYPDJbZgks
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: define('WP_HOME', 'http://' . $$_SERVER['HTTP_HOST']);
        define('WP_SITEURL', 'http://' . $$_SERVER['HTTP_HOST']);
    volumes:
    - test5_wp_data:/var/www/html
    networks:
    - test5_network
volumes:
  test5_db_data: {}
  test5_wp_data: {}
networks:
  test5_network:
    driver: bridge
