version: '3.8'
services:
  test1_db:
    image: mysql:8.0
    container_name: test1_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: vwbNZEwiqesRPiMV
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: vwbNZEwiqesRPiMV
    volumes:
    - test1_db_data:/var/lib/mysql
    networks:
    - test1_network
  test1_wordpress:
    depends_on:
    - test1_db
    image: wordpress:latest
    container_name: test1_wp
    restart: unless-stopped
    ports:
    - 9002:80
    environment:
      WORDPRESS_DB_HOST: test1_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: vwbNZEwiqesRPiMV
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
        define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
    volumes:
    - test1_wp_data:/var/www/html
    networks:
    - test1_network
volumes:
  test1_db_data: {}
  test1_wp_data: {}
networks:
  test1_network:
    driver: bridge
