<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'cZXomQWDHid66mdM' );
define( 'DB_HOST', 'test13_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         'wv8%-mwaVxS69o=CtVQuJHX=*KoL>{uIXSYt=[_!2T#Z5afj0=x9FspQ]7QKVC9i' );
define( 'SECURE_AUTH_KEY',  '5<5!Z8uBL=HIZb@Oy9@O6)I4pcuCrj2lp[HirACnGDR@K$4RHb1SxCy]BON){nAn' );
define( 'LOGGED_IN_KEY',    'mM!aDDkf$zbjxTji$CYS8vss^nu7jm51KB57JO79Oo]i7%=>9SXqe@W6GNZJw4w9' );
define( 'NONCE_KEY',        'zMr%(@RC^Q9Szo-zPG#lOGRQ0]ZDBH-dt#)J10d4g3$({MkO%*hBYr33J{oSX9&1' );
define( 'AUTH_SALT',        'z[rpxb7@F=M9Lyt!#s1{]pfHtVwhX*_GRCqQ14NW_Wtz3EqI)r[fOM*p4ZQsjE!Q' );
define( 'SECURE_AUTH_SALT', 'BtoftRrMHXYZjwFQc6pov^R0taL]N@]*vj*k5N&M)kZP-cUzD<ntJ<x75BxN_z)[' );
define( 'LOGGED_IN_SALT',   '!*ZDW66B1R@fX5bIMLe(&${FNhC2@@Etpt#sFTfaTSPmh7Og^oj%ST8t01<3&-rH' );
define( 'NONCE_SALT',       '94LP(2I>v^SpfYjWA5zz&xD-1xTY5R3(vY<-oI5VF3S4Vn(Q)>Il6uF>MP3yRm-5' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
