<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', '17uA5AZgForLYgfC' );
define( 'DB_HOST', 'test17_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         'qNy2B0}_I>T@FQShx$d}E2RnoZc6r15dIEeSrR($fx}GTK>SwN!G][}JIY(tLW%E' );
define( 'SECURE_AUTH_KEY',  'x6tEMx^${NwFjmW5!J6Ut3t@6SHihp4Uar(uOnU2rEM)L{4#Fq{2v8IU_Kc6)w$0' );
define( 'LOGGED_IN_KEY',    'QFiYJ71sNPd1Ex(eQ(^M)Pwt3dyIH%uCJ]Ff&k=Z3G#sYQ&#h>!C!iQ9SGusbsyc' );
define( 'NONCE_KEY',        'tzUUz&YG702}Z3*rJdgIqAf2hYgBAkNaP1=7HXP}UJ*>xCD}e]*R4G{al}a{o89(' );
define( 'AUTH_SALT',        '4&*m0UCGlSMIH-2$IFOt8lHwWu>ZggYOSu)Tut{@i4Ot8Lxj[N!)*0%]O<O%oFxL' );
define( 'SECURE_AUTH_SALT', 'MSPG}}fo=[V0woubu28[vZ-Co9bH@gx2q>f#3JZS-CzAM6!HdFc%hc*Fz<c6f{$0' );
define( 'LOGGED_IN_SALT',   '4MtWp[!NArM8LwXg<Dnu{H&z4pUMB6%ZpD8#9_VdK0yw<%yse_A>}bzZSPU(YMl[' );
define( 'NONCE_SALT',       'B)Red_OTmIhhD8xql)$TY6(1_}sJo5cp)xyA@Ek>E(7>qg{[{IF@Y{n[k3v3rE_t' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
