version: '3.8'
services:
  test19_db:
    image: mysql:8.0
    container_name: test19_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Pi6sXiVbsEOiPhEv
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Pi6sXiVbsEOiPhEv
    volumes:
    - test19_db_data:/var/lib/mysql
    networks:
    - test19_network
  test19_wordpress:
    depends_on:
    - test19_db
    image: wordpress:latest
    container_name: test19_wp
    restart: unless-stopped
    ports:
    - 9001:80
    environment:
      WORDPRESS_DB_HOST: test19_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Pi6sXiVbsEOiPhEv
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - test19_wp_data:/var/www/html
    networks:
    - test19_network
volumes:
  test19_db_data: {}
  test19_wp_data: {}
networks:
  test19_network:
    driver: bridge
