<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'Pi6sXiVbsEOiPhEv' );
define( 'DB_HOST', 'test19_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         '-L[h=#{R_j2*Zf@Z[wX_@J8Ff6tfFjZALp$9(*r2LjoigOb[I3=OChgfbN[rk)#u' );
define( 'SECURE_AUTH_KEY',  '[qrsS]>gOZvNr4p<fjknutd})hwl[fZG9Ug>$I1z}CuIefjcZBArWOmUFp-i{D5E' );
define( 'LOGGED_IN_KEY',    '2$=Gm]j&-h<SBthv%%c>kDy_OR1IbR0j}[!4cD_a*IIWumJaiZX]gO897{9PY<&J' );
define( 'NONCE_KEY',        'B2}!v&jDGeXgxjqvwGZO}G(Qk^SpTB9z<my78!}!oQmcL0Y!WVw{DQkCh91fHXP^' );
define( 'AUTH_SALT',        'H)de$-qddu_)<[jVOwka}7N=rOWVU6P2-5>%(]WV{MC0zfaA)lLXw5QkN2KQ>SRX' );
define( 'SECURE_AUTH_SALT', 'K=x$nD(3uP8sS!$g5OaEGt4zePoP9JmS]>b4k0j(3&EX(W=TK3q4Q5wfTA3V32u$' );
define( 'LOGGED_IN_SALT',   'aP]XdOYw}@YU4CutcR)hcuw%}PvLG%@6fRkouApRyq5zTODEjeo8E>*l482mGNA*' );
define( 'NONCE_SALT',       'k*}a4^CJdfi(nK&G1FC]wziT9X]bqi*Eh18ij)-Y71@n46%Yr$5Kdf@Z}>eY-pVs' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
