<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'wordpress' );
define( 'DB_HOST', 'test19_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         '2HFmh#GL)IR9%oIiyU9XkXMO2eMMNoZy9!6j]Jv4FB9W3e=JPv5>@DV{vfV(O^Ii' );
define( 'SECURE_AUTH_KEY',  'WMc9M98dsTH6D9*CO}ALPO&uyeDfEVL-L-&9<S0Nbg__3O6wS)VJfTWHm@f$hn]@' );
define( 'LOGGED_IN_KEY',    '6%3$$zr89]I2@}_P(@6a9)O^f2ee{HHS[3}ZJAwzoAVMAhbQOXbI1VDsXB]EFga5' );
define( 'NONCE_KEY',        'i!6sn6j7>=j49c%8o*SKMGqrlOx{1u{[(IxYJ$6^p-r!kF7nEG@)k08_Tl1kbE%o' );
define( 'AUTH_SALT',        'CKh]0}9(1q@T^)OnzewG]hyXid%-$DJU2tZ[^o>YFEO9RPR3yN*bxzX9FwH9J>G*' );
define( 'SECURE_AUTH_SALT', '}nBuXLAoUyu(@$%Povrf%lUtEs)>}]owEdWfIPQ1%TVe=djcmFJOiNa#u&iq&QvH' );
define( 'LOGGED_IN_SALT',   'Pt=&gpPehR]TA&3eC(y]QDgufSYXH2fCl2GrV$anKzAsX1S&@Pcv#_-eJLnH_PL)' );
define( 'NONCE_SALT',       'o![ayT>(7R3V4oTj_vDPUKZhc)b2CtdOAs6SUW(K)*Ju-)fT80WUtrg]Gg6Sv&qD' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
$protocol = 'http';

// Detect HTTPS from various sources (Cloudflare Tunnel, reverse proxy, etc.)
if (
    (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ||
    (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') ||
    (!empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] === 'on') ||
    (!empty($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == 443)
) {
    $protocol = 'https';
    $_SERVER['HTTPS'] = 'on';
}

if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', $protocol . '://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', $protocol . '://' . $_SERVER['HTTP_HOST']);
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
