version: '3.8'
services:
  adi_db:
    image: mysql:8.0
    container_name: adi_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: lniO9e7jeXGksRwS
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: lniO9e7jeXGksRwS
    volumes:
    - adi_db_data:/var/lib/mysql
    networks:
    - adi_network
  adi_wordpress:
    depends_on:
    - adi_db
    image: wordpress:latest
    container_name: adi_wp
    restart: unless-stopped
    ports:
    - 9000:80
    environment:
      WORDPRESS_DB_HOST: adi_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: lniO9e7jeXGksRwS
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - adi_wp_data:/var/www/html
    networks:
    - adi_network
volumes:
  adi_db_data: {}
  adi_wp_data: {}
networks:
  adi_network:
    driver: bridge
