<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'Xvv1Gh4DsG9ct17O' );
define( 'DB_HOST', 'test23_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         'Ky*y(Dg8)#mCCA-p%#GXlRIVR}#Oz(QQIWgS9$)dhJ1[4{uocl=&fC@ZhXLri<KH' );
define( 'SECURE_AUTH_KEY',  'Afxb@A7^0!vg$TeLNlqoU*xDoS1pFRo]@)>BR2^aBK%7^Xqo2BGk5vn@r@V!>TPy' );
define( 'LOGGED_IN_KEY',    '6qKqX=gaIXk<i2_[S$^(1TExMy-rzwXj$kaoSTmVkA^#9<l-]IWh5T@r]2aesjw9' );
define( 'NONCE_KEY',        'EiTh!9nwOT>@MG>]RO0sM81Z[&uWlNoz9YMTk-*Y8bxIgdWPSe!RU1qg-HXE%^{o' );
define( 'AUTH_SALT',        '#bm#]nR5GI#X[2rRXWjpBmLSBT(&zRDIb={MhJ!0jYB<!(n>YNgQ6RaBVtgojaXV' );
define( 'SECURE_AUTH_SALT', 'Eph}GunzrYE6G!a6QDZ=^{!AAscTleTQi=s$sWfN_q4u=k*OMqa8i9%Xtfb#J9Gc' );
define( 'LOGGED_IN_SALT',   'w%09F_5dWh%P3AAX>bw=n=mZAI6HnK-$-U6J{sC^_7RanAV9*_mwNvpEZ=k_nmP0' );
define( 'NONCE_SALT',       '7jDwU4}Y0x{{laC)#S6Ejt^!VsVt6kwHWN7-HxKSHTlcqr>O$>7%}S8u6l<Umia@' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
