<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'wordpress' );
define( 'DB_HOST', 'test23_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         'jSssUPagkwLx>VyIjYvVr&iQjeuMd!iH5vYPw%X0}(P}r4b<gIYZ[Zh{-0}pI%CP' );
define( 'SECURE_AUTH_KEY',  'REo4O8Q2yC2CqF!L*KdMR^Yi]V9NJc(L!Kf6O3TQJ8*{dX}G3TZ3@Rroe<]([2A<' );
define( 'LOGGED_IN_KEY',    'X}FAl*K4[BcRFxjFE4^!$Rus2zj#81zlNgD&MV%8cmU0am3sKL=jWcg&lA}BmtA(' );
define( 'NONCE_KEY',        '#_q2$9Sj7KG0OR*v&TT0D4R{iSu7BXJf03}5m%f_Y34B<Q07wYN]9F<8!jV5cUk%' );
define( 'AUTH_SALT',        '$@Aalzf$*RAq(@nPsfk_o^#^u09!fx#<lVaWhCLn[OWcEC%{Q[T2c94Ubjt0]cNp' );
define( 'SECURE_AUTH_SALT', 'Cm%[tYzXTBz>Gg91%!XI{DD<U}^wOa7qJe5JuKZ=]L&6ufjz{@*8kkVoSfYHwavD' );
define( 'LOGGED_IN_SALT',   'Ogv#(F=r]>OC^YTy*}NCPUPaIj#Gx*y1t7wL@Gig>!@*tFAFgu&qBT0*=FVsnV-w' );
define( 'NONCE_SALT',       'y-E1-plbdpk(Td1JEY&}ir{kUKa*r7zdePbhk<!utkF$[Tldk@kgt5zP#-WL>@vd' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
$protocol = 'http';

// Detect HTTPS from various sources (Cloudflare Tunnel, reverse proxy, etc.)
if (
    (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ||
    (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') ||
    (!empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] === 'on') ||
    (!empty($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == 443)
) {
    $protocol = 'https';
    $_SERVER['HTTPS'] = 'on';
}

if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', $protocol . '://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', $protocol . '://' . $_SERVER['HTTP_HOST']);
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
