# Generated by Django 5.2.10 on 2026-01-29 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordPressSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('port', models.IntegerField(unique=True)),
                ('admin_username', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='provisioning', max_length=20)),
                ('container_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_directory', models.CharField(max_length=500)),
                ('docker_compose_path', models.CharField(max_length=500)),
                ('nginx_config_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'WordPress Site',
                'verbose_name_plural': 'WordPress Sites',
                'ordering': ['-created_at'],
            },
        ),
    ]
