# Generated by Django 5.2.10 on 2026-02-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress_sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='tunnel_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='tunnel_process_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='tunnel_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
