# Generated by Django 5.2.10 on 2026-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_wordpresssite_tunnel_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordpresssite',
            old_name='tunnel_active',
            new_name='public_access_enabled',
        ),
        migrations.RenameField(
            model_name='wordpresssite',
            old_name='tunnel_url',
            new_name='public_url',
        ),
        migrations.RemoveField(
            model_name='wordpresssite',
            name='tunnel_process_id',
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='subdomain',
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
