# Generated by Django 5.2.10 on 2026-02-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_rename_tunnel_active_wordpresssite_public_access_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='db_container_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='db_container_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='db_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='db_name',
            field=models.CharField(default='wordpress', max_length=100),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='db_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='db_root_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='db_user',
            field=models.CharField(default='wordpress', max_length=100),
        ),
    ]
