# Generated by Django 5.2.10 on 2026-02-10 11:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress_sites', '0004_wordpresssite_db_container_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('cloudflare_zone_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nameservers', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Nameserver Update'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='wordpress_sites.wordpresssite')),
            ],
            options={
                'verbose_name': 'Custom Domain',
                'verbose_name_plural': 'Custom Domains',
                'ordering': ['-created_at'],
            },
        ),
    ]
