# Generated by Django 5.2.10 on 2026-02-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress_sites', '0005_customdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='filebrowser_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='filebrowser_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
