# Generated by Django 5.2.10 on 2026-02-20 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress_sites', '0009_userprofile_alter_projectmembership_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='api_port',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='branch',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='build_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('building', 'Building'), ('deploying', 'Deploying'), ('failed', 'Failed'), ('running', 'Running')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='env_vars',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='framework',
            field=models.CharField(choices=[('wordpress', 'WordPress'), ('react_django', 'React + Django'), ('node', 'Node.js')], default='wordpress', max_length=20),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='repo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
