# Generated by Django 4.2.28 on 2026-02-23 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordpress_sites', '0010_wordpresssite_api_port_wordpresssite_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('project_created', 'Project Created'), ('project_deleted', 'Project Deleted'), ('project_started', 'Project Started'), ('project_stopped', 'Project Stopped'), ('member_invited', 'Member Invited'), ('member_removed', 'Member Removed'), ('env_updated', 'Environment Updated'), ('backup_created', 'Backup Created'), ('backup_restored', 'Backup Restored'), ('public_access_enabled', 'Public Access Enabled'), ('public_access_disabled', 'Public Access Disabled'), ('domain_connected', 'Domain Connected'), ('domain_removed', 'Domain Removed'), ('container_restart', 'Container Restart'), ('terminal_access', 'Terminal Access'), ('database_access', 'Database Access'), ('file_access', 'File Access'), ('login', 'User Login'), ('logout', 'User Logout'), ('password_reset', 'Password Reset'), ('settings_updated', 'Settings Updated'), ('malware_detected', 'Malware Detected')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('project', 'user')},
        ),
    ]
