# Generated by Django 4.2.28 on 2026-02-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress_sites', '0011_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='replica_count',
            field=models.IntegerField(default=1),
        ),
    ]
