# Generated by Django 4.2.28 on 2026-03-02 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordpress_sites', '0013_wordpresssite_backend_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='gateway_config_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='gateway_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='gateway_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('container_name', models.CharField(max_length=120)),
                ('internal_port', models.PositiveIntegerField(default=8000)),
                ('protocol', models.CharField(choices=[('http', 'HTTP')], default='http', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_services', to='wordpress_sites.wordpresssite')),
            ],
            options={
                'verbose_name': 'Project Service',
                'verbose_name_plural': 'Project Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApiRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('strip_prefix', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_routes', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='wordpress_sites.projectservice')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_routes', to='wordpress_sites.wordpresssite')),
            ],
            options={
                'verbose_name': 'API Route',
                'verbose_name_plural': 'API Routes',
                'ordering': ['path'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectservice',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='uniq_project_service_name'),
        ),
        migrations.AddConstraint(
            model_name='projectservice',
            constraint=models.UniqueConstraint(fields=('site', 'container_name', 'internal_port'), name='uniq_project_service_target'),
        ),
        migrations.AddConstraint(
            model_name='apiroute',
            constraint=models.UniqueConstraint(fields=('site', 'path'), name='uniq_project_api_path'),
        ),
        migrations.AddConstraint(
            model_name='apiroute',
            constraint=models.CheckConstraint(check=models.Q(('path__startswith', '/api/')), name='api_route_must_start_with_api_prefix'),
        ),
    ]
