# Generated by Django 4.2.28 on 2026-03-02 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordpress_sites', '0014_wordpresssite_gateway_config_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('worker_id', models.CharField(blank=True, default='', max_length=120)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_apply_jobs', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_apply_jobs', to='wordpress_sites.wordpresssite')),
            ],
            options={
                'verbose_name': 'Gateway Apply Job',
                'verbose_name_plural': 'Gateway Apply Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='wordpress_s_status_3d74be_idx'), models.Index(fields=['site', '-created_at'], name='wordpress_s_site_id_337631_idx')],
            },
        ),
    ]
