# Generated by Django 5.2.10 on 2026-03-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress_sites', '0015_gatewayapplyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='db_dr_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
