# Generated by Django 4.2.28 on 2026-03-10 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordpress_sites', '0016_wordpresssite_db_dr_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('vcpu', models.PositiveSmallIntegerField(default=1)),
                ('memory_mb', models.PositiveIntegerField(default=1024)),
                ('disk_gb', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compute Flavor',
                'verbose_name_plural': 'Compute Flavors',
                'ordering': ['vcpu', 'memory_mb', 'disk_gb'],
            },
        ),
        migrations.CreateModel(
            name='ComputeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(default='latest', max_length=60)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('local_path', models.CharField(help_text='Absolute path to immutable cloud image', max_length=500)),
                ('os_family', models.CharField(choices=[('ubuntu', 'Ubuntu'), ('debian', 'Debian'), ('centos', 'CentOS'), ('rocky', 'Rocky Linux'), ('other', 'Other')], default='ubuntu', max_length=30)),
                ('minimum_disk_gb', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compute_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compute Image',
                'verbose_name_plural': 'Compute Images',
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComputeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('instance_id', models.CharField(blank=True, default='', max_length=24, unique=True)),
                ('state', models.CharField(choices=[('provisioning', 'Provisioning'), ('pending', 'Pending'), ('running', 'Running'), ('stopped', 'Stopped'), ('starting', 'Starting'), ('stopping', 'Stopping'), ('rebooting', 'Rebooting'), ('terminating', 'Terminating'), ('terminated', 'Terminated'), ('error', 'Error')], default='provisioning', max_length=20)),
                ('desired_state', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('terminated', 'Terminated')], default='running', max_length=20)),
                ('private_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('libvirt_domain_name', models.CharField(blank=True, default='', max_length=255)),
                ('libvirt_domain_uuid', models.CharField(blank=True, default='', max_length=64)),
                ('disk_path', models.CharField(blank=True, default='', max_length=500)),
                ('seed_iso_path', models.CharField(blank=True, default='', max_length=500)),
                ('cloud_init_completed', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='wordpress_sites.computeflavor')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='wordpress_sites.computeimage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compute_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compute Instance',
                'verbose_name_plural': 'Compute Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Group',
                'verbose_name_plural': 'Security Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SSHKeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('public_key', models.TextField()),
                ('fingerprint', models.CharField(blank=True, default='', max_length=95)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_key_pairs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSH Key Pair',
                'verbose_name_plural': 'SSH Key Pairs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityGroupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('ingress', 'Ingress'), ('egress', 'Egress')], default='ingress', max_length=10)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('all', 'All')], default='tcp', max_length=10)),
                ('from_port', models.PositiveIntegerField(blank=True, null=True)),
                ('to_port', models.PositiveIntegerField(blank=True, null=True)),
                ('cidr', models.CharField(default='0.0.0.0/0', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='wordpress_sites.securitygroup')),
            ],
            options={
                'verbose_name': 'Security Group Rule',
                'verbose_name_plural': 'Security Group Rules',
                'ordering': ['direction', 'protocol', 'from_port'],
            },
        ),
        migrations.CreateModel(
            name='ComputeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('create', 'Create'), ('start', 'Start'), ('stop', 'Stop'), ('reboot', 'Reboot'), ('terminate', 'Terminate'), ('describe', 'Describe'), ('reconcile', 'Reconcile')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=80)),
                ('error', models.TextField(blank=True, default='')),
                ('worker_id', models.CharField(blank=True, default='', max_length=120)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='wordpress_sites.computeinstance')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compute_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compute Operation',
                'verbose_name_plural': 'Compute Operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='computeinstance',
            name='security_groups',
            field=models.ManyToManyField(blank=True, related_name='instances', to='wordpress_sites.securitygroup'),
        ),
        migrations.AddField(
            model_name='computeinstance',
            name='ssh_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='wordpress_sites.sshkeypair'),
        ),
        migrations.CreateModel(
            name='ComputeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compute_events', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wordpress_sites.computeinstance')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='wordpress_sites.computeoperation')),
            ],
            options={
                'verbose_name': 'Compute Event',
                'verbose_name_plural': 'Compute Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sshkeypair',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_owner_ssh_key_name'),
        ),
        migrations.AddConstraint(
            model_name='sshkeypair',
            constraint=models.UniqueConstraint(fields=('owner', 'fingerprint'), name='uniq_owner_ssh_key_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='securitygroup',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_owner_security_group_name'),
        ),
        migrations.AddIndex(
            model_name='computeoperation',
            index=models.Index(fields=['status', 'scheduled_for'], name='wordpress_s_status_68b0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='computeoperation',
            index=models.Index(fields=['instance', '-created_at'], name='wordpress_s_instanc_e96986_idx'),
        ),
        migrations.AddIndex(
            model_name='computeoperation',
            index=models.Index(fields=['idempotency_key'], name='wordpress_s_idempot_5670c3_idx'),
        ),
        migrations.AddIndex(
            model_name='computeinstance',
            index=models.Index(fields=['owner', 'state'], name='wordpress_s_owner_i_e2174e_idx'),
        ),
        migrations.AddIndex(
            model_name='computeinstance',
            index=models.Index(fields=['instance_id'], name='wordpress_s_instanc_af2911_idx'),
        ),
        migrations.AddConstraint(
            model_name='computeinstance',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_owner_compute_instance_name'),
        ),
        migrations.AddConstraint(
            model_name='computeimage',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniq_compute_image_name_version'),
        ),
        migrations.AddIndex(
            model_name='computeevent',
            index=models.Index(fields=['instance', '-created_at'], name='wordpress_s_instanc_2edf1b_idx'),
        ),
        migrations.AddIndex(
            model_name='computeevent',
            index=models.Index(fields=['event_type', '-created_at'], name='wordpress_s_event_t_f9853b_idx'),
        ),
    ]
