# Generated by Django 4.2.28 on 2026-03-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress_sites', '0017_computeflavor_computeimage_computeinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeoperation',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computeoperation',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computeoperation',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='computeoperation',
            name='retry_backoff_seconds',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
