version: '3.8'
services:
  test9_db:
    image: mysql:8.0
    container_name: test9_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 4lK9ScE55GDmF8mL
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 4lK9ScE55GDmF8mL
    volumes:
    - test9_db_data:/var/lib/mysql
    networks:
    - test9_network
  test9_wordpress:
    depends_on:
    - test9_db
    image: wordpress:latest
    container_name: test9_wp
    restart: unless-stopped
    ports:
    - 9005:80
    environment:
      WORDPRESS_DB_HOST: test9_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 4lK9ScE55GDmF8mL
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - test9_wp_data:/var/www/html
    networks:
    - test9_network
volumes:
  test9_db_data: {}
  test9_wp_data: {}
networks:
  test9_network:
    driver: bridge
