<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', '4lK9ScE55GDmF8mL' );
define( 'DB_HOST', 'test9_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         'vvp6a!4ODI^h]#nXs@o{q6$Pw&-pn*1^#)b5F(Ask9tHG$r<da6x[{&55[Y$)*C>' );
define( 'SECURE_AUTH_KEY',  '$#OxJ<#CA2o2%Nh-(KI34L3b_*_}!xIv}TCpYNXsi^ffY-w%j8oPqF1IN<-UUU*{' );
define( 'LOGGED_IN_KEY',    'Ai]s*5aRMK>NLhlA&tPz$h]NUFYM*3nEk(IrW[lb>Ur7IiH_N%rm3)%GQX5o=5NF' );
define( 'NONCE_KEY',        'y0N&]fKn4gylFp$2[84-w>A2!*aO8biTllnvQux6yxyW%@>Jx1D[X6h{l}ok!HZ(' );
define( 'AUTH_SALT',        'Z@FC!G&0N>P$QPBCO-af6{GZC!<8Dj%qn--4UkAHYxWg9I<LR#SVpIviY%tagY4u' );
define( 'SECURE_AUTH_SALT', 'sN)zt#Y5xLRHu@b$rgIoUQ@t$9o>9Rxy3eus-S7($Xd2>bVTNUUT#m!gx%*VFOhW' );
define( 'LOGGED_IN_SALT',   'PwIx(ZT{5ndu!qvCC>{k*TO{PW8T>sioz#J2xJ20t^@f6g$TIP37<G-64wyweLFW' );
define( 'NONCE_SALT',       'E8163we(Q$!U&S4<QkWXt]^9B{9W2^2l0<GlAqdSM3pH8$ZD{6[XzY4sNdh7&S2#' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );
// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);


// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
