<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'ondiEYhklRUJW6ZU' );
define( 'DB_HOST', 'test10_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         'wFyZoGAjes>9*&bgClMld#wZK*bB*VI{7h(k*KA8<n%xFZTg1B8K1KO)U%sNe(yX' );
define( 'SECURE_AUTH_KEY',  'kpHxq$Nps2v3!KL!UQ4XDM<^ojME7rd-nI=cE0)pI>l}sGr6r%A9uNDEG*KgaV)G' );
define( 'LOGGED_IN_KEY',    'naw]Pc6mTa{&Lb$@9qH9$UQ-ZaO3!hTf82cKwKMUJsYsyFG9[EwlqrwsRAXK6!)!' );
define( 'NONCE_KEY',        'j$gXrowHOX^dR}-h}=RtM}j>eRVxyNeQR$fPB![2Ro)]sz4BO5[)5tB8hIF#-cMe' );
define( 'AUTH_SALT',        '=C6la#bw7=O=N6y%4T=trO#Qkdyfw2<Nn!OPSg8T-l5@A#o{c)>KEBFG=I7naOR-' );
define( 'SECURE_AUTH_SALT', 'FQ[i6qARgWHLnOJSNg#m6b%e0&Qv(_Dw2&x#BvK3H=ZHcu>[_TNP)mswoLVtSJG(' );
define( 'LOGGED_IN_SALT',   'f<0kcSYroGQST@W{[0r$uftVM$L!WGsn8J6_ZmJ3gPQ#H$B9HMHIM9i-o_)_J=Zy' );
define( 'NONCE_SALT',       'N#QtZe)Z&=-XRSAz!&hzd>YF]h1!Xmkx>Ouqt7cp-LgT%t3]c-sddpxf]PoRM^vg' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
