version: '3.8'
services:
  test24_db:
    image: mysql:8.0
    container_name: test24_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 0r0wCqEkrmTiHn17
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 0r0wCqEkrmTiHn17
    volumes:
    - test24_db_data:/var/lib/mysql
    networks:
    - test24_network
  test24_wordpress:
    depends_on:
    - test24_db
    image: wordpress:latest
    container_name: test24_wp
    restart: unless-stopped
    ports:
    - 9004:80
    environment:
      WORDPRESS_DB_HOST: test24_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 0r0wCqEkrmTiHn17
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - test24_wp_data:/var/www/html
    networks:
    - test24_network
volumes:
  test24_db_data: {}
  test24_wp_data: {}
networks:
  test24_network:
    driver: bridge
