<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', '0r0wCqEkrmTiHn17' );
define( 'DB_HOST', 'test24_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         '2rZ($QtP3c[_=1OB=)&a4iB%fy^sAz0Zcl<jG-7iv{PqA1(2m^ZZ8[2HA@ML$WGr' );
define( 'SECURE_AUTH_KEY',  'EhN$54BA3!K8{BpBdd**Hs0li6>kYCLg<-wWPMgx>3eB]^GrUXPY8]ZQl={F_-hT' );
define( 'LOGGED_IN_KEY',    'WTvDa(oehSyH^0QR8u6S2O_m(^BVvZ9fxi*j]30pMu%sBT(bs)Rwm4}@=-W=MbD-' );
define( 'NONCE_KEY',        'FH__>[^XE20Z6kLPz!KrAN0sOK1v(_&6isv]8W64gvTbE0gd(%>L(zM&T<p8zyUE' );
define( 'AUTH_SALT',        '1qKIZyXrF[g$eGcMqWas)gF%zFIw[<jB)CH!g=i*zx#([^vf#wAmmi5e_6hi!=Zp' );
define( 'SECURE_AUTH_SALT', '1DjvH$NCHTNOQ9i$WSJJOvJzh$#K*LT*dWkg4I5c-RLr-#g<v-Xuz06RegnF**tv' );
define( 'LOGGED_IN_SALT',   'R4[Wv]3MV>%xtH<jP]*hzV]Bqz$hvHgj{jXHXqBpLjDzOsoJ}Ce)boHhUn{{szIF' );
define( 'NONCE_SALT',       'Nc&(IOpTH9!J{&MyCc(Y<5EA9Xh{PNw_z=ZdkVZ^[8a]Q=kPmR]0Dt{1<giH0jXF' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
