<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'pRbK7bgZ6AXPIeoO' );
define( 'DB_HOST', 'test11_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         '(%4n$M1yWMna3TCU-@yfEP!obdb2Yufj*i6PE&wrIH3PThB}Z5WK{RrxneyQ($dK' );
define( 'SECURE_AUTH_KEY',  '0mjuv90j*g_<vL)0_>_b%&5zCzot$}W{uiydrO4!8Jpjnphlo}dq#yhc)kM>3w$P' );
define( 'LOGGED_IN_KEY',    '3IfM>dP*t{e>7M]CIX<VdmpSwm%)Eoi8YTwz*}_v7f9M{Ib3wBe[c)z@Px5c$fd4' );
define( 'NONCE_KEY',        'OETT4-=F7-ym}d$(*tC#p>3ZIoqbZd{[3l[XN>i{0JqG4GxoPSONuNS3hpU}aPKw' );
define( 'AUTH_SALT',        'GnH[J^CVvXnLnL4*$43^F@M-$p>qs_H5ie<*I@BB5EdspLz!F]omKV8@G6D57KD(' );
define( 'SECURE_AUTH_SALT', 'mRP70MbQxlt2Va!Sb}vpR_hkni3E3*MsC=M5)Zf@[NZmH6TVxp*>*}aQmXvpw^^>' );
define( 'LOGGED_IN_SALT',   '!No>YAUZVkoDlKSXr!ERR{4^E_@U(N3anp%Js2x3i1DnU$MtjElzv3v82jai2t30' );
define( 'NONCE_SALT',       'flFg}-5g4iRv3B5L=dCoN6MfHKCT$hyMPs6H!hW%R7#$)]-0BEPIuEu>@j}0ms&j' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );
// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);


// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
