<?php
// DEBUG MARKER
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'CQNIl3j679jLNUdF' );
define( 'DB_HOST', 'test8_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         'B]1q{Q!oC_BWxE{Z6Njd@gdnL<UKt$a@fRx4A)m1Er4-@^9!F&n!gLDIE{X_ecuf' );
define( 'SECURE_AUTH_KEY',  'GqwHfQ9ldU0sXivl15CmIe(TxJ1iw68C!Pe$l)_tWTo9c2Cnib{GTJrGRhinqaOt' );
define( 'LOGGED_IN_KEY',    'l6p-MjhLfn]<<QQdWPR}trKT4=hK&kz<@Ll#{o1ELDGXny}R98uHfFyze#XU6gDE' );
define( 'NONCE_KEY',        'aZK&wyzoXwOo[zq6HbFYElODBkp$Ah5g^09s8tWW2kQ6LtOt*^Yg-LAZAsVNmxcW' );
define( 'AUTH_SALT',        '8t7MrZATzhfNB7yO-vB6#ftfLdg8F9v&g<1cR$tOdN)bUFm_oUqE^9NFzn4_o5q(' );
define( 'SECURE_AUTH_SALT', '[Q<t&oowI{L4gK]#m<-^Dvk3MhPL[kApQj^pXeMfpr<yi_tN4eSP)fF&l2>$VU2G' );
define( 'LOGGED_IN_SALT',   'Y!zPnK#@7IuAY0iUyS{_}nODq2Y[I<]06TGjslB&5U<=7Rlp^#)Vf<pD_}dld@7P' );
define( 'NONCE_SALT',       'ZICM&-YjmPeL1ES9Mb(WM8!x=>a_Zk1ILuLA!#15sA>qnH9PsY0<lKxk9o&o]{(Y' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );
// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);


// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
