version: '3.8'
services:
  test20_db:
    image: mysql:8.0
    container_name: test20_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: KHOV1u9a2DgJZwLm
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: KHOV1u9a2DgJZwLm
    volumes:
    - test20_db_data:/var/lib/mysql
    networks:
    - test20_network
  test20_wordpress:
    depends_on:
    - test20_db
    image: wordpress:latest
    container_name: test20_wp
    restart: unless-stopped
    ports:
    - 9002:80
    environment:
      WORDPRESS_DB_HOST: test20_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: KHOV1u9a2DgJZwLm
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - test20_wp_data:/var/www/html
    networks:
    - test20_network
volumes:
  test20_db_data: {}
  test20_wp_data: {}
networks:
  test20_network:
    driver: bridge
