<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'KHOV1u9a2DgJZwLm' );
define( 'DB_HOST', 'test20_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         '5UUTucqs}E^EbU<*<&*{Z9C{t%9JtS_)!11z-A@mrpgyEWSKwp6j(EYks{hf@M%w' );
define( 'SECURE_AUTH_KEY',  'xRNHCcK}eh#skbv)mhM$>wcafFE6_y}$bewGj05ItYy8)dNuXVxA7_S<1vE4ZfP@' );
define( 'LOGGED_IN_KEY',    'gb=@0nKUP6]9)]b_rQe2vK0Qrq1=CjYI*wN6{P7ZhfJbqi*m_m59td>inpQvK3su' );
define( 'NONCE_KEY',        'rMFnJBfK5]V-B@E8>_CWvA#!mQ=Wv)e4$CS*JODjXP&P!L{k=aaVtV7VDW-WQnHu' );
define( 'AUTH_SALT',        'Ix<T8IC2rWTH33pHZsP(j#UoTCh3oc*L_w8AD!O26FaYj8*h@=KtJPyRT=c]xRQR' );
define( 'SECURE_AUTH_SALT', 'yhB7=$Z)2CjpMfOVzCVDlf&qDrwJjZ_IV0*X4I#kXrgwALIC@(7J=bhnuW<NkvYb' );
define( 'LOGGED_IN_SALT',   'jh1%CB2GDlerxg<PoLAx@eGgDM4]Y3KUKJsE(M)V(vG4G9f4eYT2D0a05*LnV(r#' );
define( 'NONCE_SALT',       'BP$oMek2N1MO!^vkjXGwxO@{*OC3bzY[]N_Vh^gD35zzf3(Xmt=ea7>f)5T#@YYM' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
}

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS'] = 'on';
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
