<?php
/**
 * The base configuration for WordPress
 *
 * This file was auto-generated by the Host Orchestrator.
 */

// ** Database settings ** //
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'wordpress' );
define( 'DB_HOST', 'test20_db:3306' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 */
define( 'AUTH_KEY',         'd4Z=}wdgaAbC@u!E2*obxD_s3VKrzSy%ssMzElqX&1t2qKa_3Wue@^]Fs}@*a%0h' );
define( 'SECURE_AUTH_KEY',  've19cjPPBYtpB%vOQ#4l=P05B-a@i75M88h4N@VnWrZsWWPsmkDos=-(HnJB>3ne' );
define( 'LOGGED_IN_KEY',    'zwgx]KDTHVM780]-^-Ho=qgfrgpvLjPz(B{HhWLKk1ibmoSQpPUkApK<U7uMPzX{' );
define( 'NONCE_KEY',        'A}o!oEj1ic0@4[0n3VZXn{=n@Z#AT3rOlA<bv])!Oc&pTE@gG<yT3]P9sny62e!&' );
define( 'AUTH_SALT',        'cZ7#lSC5%zHJ$$^CGITcSQyh0>BRK7c8ZMz{J{@aTBK>yh61#!25*$x!}IFD12B{' );
define( 'SECURE_AUTH_SALT', 'sp**lL0a{>a7y^c(19=((qnf%DnFHXgRkqZkh$Q@EGb0SQ^ySRPJad0p^y_19}uw' );
define( 'LOGGED_IN_SALT',   '78t}-G4q*Y>JLPvj0nQd#<30wDXi[xhHT5#8<h8eWt7wtZ=l([CU%hZ=*[A<Al*N' );
define( 'NONCE_SALT',       '4%3zMk-69m780>cuSgS#_FM^L1>LL5mR8fy[PM&>QH6}%gTt@%ii_7YbB4bLwA#A' );

/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', false );

// Fix for "Plain" Admin/Dashboard in Docker
define('CONCATENATE_SCRIPTS', false);
define('SCRIPT_DEBUG', true);

// ** Dynamic Site URL Settings ** //
// This allows the site to be accessed via localhost:PORT or custom domains
$protocol = 'http';

// Detect HTTPS from various sources (Cloudflare Tunnel, reverse proxy, etc.)
if (
    (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ||
    (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') ||
    (!empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] === 'on') ||
    (!empty($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == 443)
) {
    $protocol = 'https';
    $_SERVER['HTTPS'] = 'on';
}

if (isset($_SERVER['HTTP_HOST'])) {
    define('WP_HOME', $protocol . '://' . $_SERVER['HTTP_HOST']);
    define('WP_SITEURL', $protocol . '://' . $_SERVER['HTTP_HOST']);
}

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
